FROM python:3.7-alpine

RUN apk update && \
    apk add --no-cache \
    gcc \
    musl-dev

WORKDIR /var/api
COPY Pipfile.lock .

RUN pip install pipenv && \
    pipenv requirements --dev > /tmp/requirements.txt && \
    pip install --no-cache-dir -r /tmp/requirements.txt

COPY . .

CMD python3 -u app/main.py